apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sk-app
  template:
    metadata:
      labels:
        app: sk-app
    spec:
      containers:
        - name: registry-container
          image: sk4k/registry-container:latest
          ports:
            - containerPort: 8761
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
---

apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8761  # Updated to match the containerPort in the Deployment
  selector:
    app: sk-app
